package com.feel.mall.db.dao;

import java.util.List;

import com.feel.mall.db.domain.MallUserFormid;
import com.feel.mall.db.domain.MallUserFormidExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MallUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    long countByExample(MallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(MallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int insert(MallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(MallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    MallUserFormid selectOneByExample(MallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    MallUserFormid selectOneByExampleSelective(@Param("example") MallUserFormidExample example, @Param("selective") MallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    List<MallUserFormid> selectByExampleSelective(@Param("example") MallUserFormidExample example, @Param("selective") MallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    List<MallUserFormid> selectByExample(MallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    MallUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    MallUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    MallUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallUserFormid record, @Param("example") MallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallUserFormid record, @Param("example") MallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_formid
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}
